Rework WrapSolidify effect
sebastianandress/Slicer-SurfaceWrapSolidify_old pull request #3
Opened 2020-04-16 05:05 UTC by lassoan

I've worked a lot on understanding and improving/adding features to this effect. Algorithm of how cavities are curved out has been reworked, as it was not very robust for complex shapes, but otherwise all the core concepts and features have been preserved.

Highlights:

- Create GUI using Qt Designer
- Add automatic cavity extraction option
- Add option to specify starting surface (to allow users to solidify any part of the segment)
- Added new algorithm for carving out cavities very robustly from arbitrarily complex shapes
- Removed a few hardcoded values (they are now computed from inputs)

It would be great if you could test it on your data sets and let me know how it works. If it looks all good then please merge this pull request.

2020-04-17 14:52 UTC, lassoan commented
@sebastianandress I've worked a _lot_ on this and would really like to make the new features and improvements available to Slicer users. When do you think you will have time to check this out?

If you prefer to keep your segment editor effect as is and have a separate effect for general use then we can do that, too, but the two modules would be somewhat redundant and there would be overall maintenance workload.

Anyway, let me know how you want to proceed.

Thanks again for your very useful and important contribution!

2020-04-17 15:45 UTC, sebastianandress commented
Dear @lassoan,
I‘m amazed by the effort you put into improving the effect. I‘ll test everything on the weekend and merge it! Thanks a lot!

2020-04-17 17:04 UTC, lassoan commented
Sounds good, thank you!

2020-04-19 10:10 UTC, sebastianandress requested changes
Dear @lassoan, thank you for these improvements. I really like that the model gets shrunken to the dilated model, it's a nice solution for my prototype approach. Also the option to start from a dedicated segment is very helpful for some applications.

The only thing that is flipped around in my eyes is the offset direction. Besides that I tested the changes for about 10 models and it worked for all of them. Thanks a lot!

2020-04-19 10:10 UTC, sebastianandress commented on SegmentEditorWrapSolidify/SegmentEditorWrapSolidifyLib/SegmentEditorEffect.py
> +    if shellOffsetDirection == SHELL_OFFSET_INSIDE:
in my tests that's wrong way round, probably this has to be SHELL_OFFSET_OUTSIDE

2020-04-19 16:28 UTC, lassoan commented
Great, thanks for testing! It would be great if you could merge it and we can update how the offset direction is specified in a follow-up commit.

2020-04-19 20:22 UTC, merged